# Generated by Django 3.0.5 on 2020-05-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Antwort', 'verbose_name_plural': 'Antworten'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Frage', 'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('-created_at',), 'verbose_name': 'Runde', 'verbose_name_plural': 'Runden'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='round',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_current_set', to='api.Question', verbose_name='Aktuelle Frage'),
        ),
        migrations.AlterField(
            model_name='round',
            name='phase',
            field=models.CharField(choices=[('question', 'Erarbeitungsphase'), ('answer', 'Fragephase'), ('scoring', 'Bewertungsphase'), ('done', 'Abgeschlossen')], default='question', max_length=30, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='round',
            name='questions',
            field=models.ManyToManyField(blank=True, to='api.Question', verbose_name='Fragen'),
        ),
        migrations.AlterField(
            model_name='round',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_as_creator', to=settings.AUTH_USER_MODEL, verbose_name='Gründer'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder'),
        ),
        migrations.AlterField(
            model_name='team',
            name='mode',
            field=models.CharField(choices=[('train', 'Training'), ('competition', 'Wettkampf')], default='train', max_length=30, verbose_name='Modus'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('open', 'offen'), ('playing', 'spielt'), ('archived', 'archiviert')], default='open', max_length=30, verbose_name='Status'),
        ),
    ]
