# Generated by Django 3.0.5 on 2020-05-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200501_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('created_at',), 'verbose_name': 'Runde', 'verbose_name_plural': 'Runden'},
        ),
    ]
