# Generated by Django 3.0.5 on 2020-05-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200501_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Round', verbose_name='Runde'),
        ),
    ]
