# Generated by Django 3.0.5 on 2020-05-02 08:36

from django.db import migrations

def remove_null_round_questions(apps, schema_editor):
    Question = apps.get_model("api", "Question")
    Question.objects.filter(round=None).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200502_1035'),
    ]

    operations = [
        migrations.RunPython(remove_null_round_questions)
    ]
