# Generated by Django 3.0.5 on 2020-05-02 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200502_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round', verbose_name='Runde'),
        ),
    ]
