# Generated by Django 3.0.5 on 2020-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200502_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
