# Generated by Django 3.0.5 on 2020-05-02 19:07

from django.db import migrations
from django.db.models import F

def migrate_module_code(apps, schema_editor):
    Topic = apps.get_model("api", "Topic")
    Topic.objects.update(code=F("id"))

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200502_2107'),
    ]

    operations = [
        migrations.RunPython(migrate_module_code),
    ]
