# Generated by Django 3.0.5 on 2020-05-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200502_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
    ]
