# Generated by Django 3.0.5 on 2020-05-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200502_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('code',), 'verbose_name': 'Thema', 'verbose_name_plural': 'Themen'},
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Round', verbose_name='Runde'),
        ),
    ]
