# Generated by Django 3.0.5 on 2020-05-10 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200509_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='round',
        ),
        migrations.AddField(
            model_name='team',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_current_set', to='api.Question', verbose_name='Aktuelle Frage'),
        ),
        migrations.AddField(
            model_name='team',
            name='questions',
            field=models.ManyToManyField(help_text='Fragen der aktuellen Runde', to='api.Question', verbose_name='Fragen'),
        ),
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.CharField(choices=[('open', 'offen'), ('question', 'Erarbeitungsphase'), ('answer', 'Fragephase'), ('scoring', 'Bewertungsphase'), ('done', 'Abgeschlossen'), ('archived', 'archiviert')], default='open', max_length=30, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
