# Generated by Django 3.0.5 on 2020-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200510_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'falsch'), (1, 'teilweise richtig'), (3, 'richtig')], null=True, verbose_name='Bewertung'),
        ),
        migrations.AlterField(
            model_name='team',
            name='questions',
            field=models.ManyToManyField(blank=True, help_text='Fragen der aktuellen Runde', to='api.Question', verbose_name='Fragen'),
        ),
    ]
