# Generated by Django 3.0.5 on 2020-05-13 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200513_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('author', 'question')},
        ),
    ]
