# Generated by Django 3.0.5 on 2020-05-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200513_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='api.Team'),
        ),
    ]
