# Generated by Django 3.0.5 on 2020-05-15 07:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20200515_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('team', 'author')},
        ),
    ]
