# Generated by Django 3.0.5 on 2020-05-15 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20200515_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.PositiveIntegerField(default=0)),
                ('partial', models.PositiveIntegerField(default=0)),
                ('wrong', models.PositiveIntegerField(default=0)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitgliedschaft',
            },
        ),
        migrations.RemoveField(
            model_name="team",
            name="members"
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='api.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder'),
        ),
    ]
