# Generated by Django 3.0.5 on 2020-05-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200515_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='done',
            field=models.BooleanField(default=False, help_text='Frage wurde von allen beantwortet', verbose_name='Erledigt'),
        ),
    ]
