# Generated by Django 3.0.5 on 2020-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_answer_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='done',
        ),
        migrations.AddField(
            model_name='question',
            name='done',
            field=models.BooleanField(default=False, help_text='Frage wurde von allen beantwortet', verbose_name='Erledigt'),
        ),
    ]
